# Usamos la imagen oficial de NGINX
FROM nginx:latest

# Copiamos el archivo de configuración de NGINX al contenedor
COPY nginx.conf /etc/nginx/nginx.conf

# Exponemos el puerto en el que correrá el API Gateway
EXPOSE 80

# Comando para ejecutar NGINX
CMD ["nginx", "-g", "daemon off;"]
