version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - ENV=production
      - DATABASE_URL=postgresql://user:password@db:5432/nutrition_db
    depends_on:
      - db
    networks:
      - app_network

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app_network

  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nutrition_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - app_network

networks:
  app_network:

volumes:
  db_data:
