services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - app_network
    volumes:
      - ./backend:/app/backend
      - ./db:/app/db
    depends_on:
      - db

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
