# Usamos una imagen oficial de Python como base
FROM python:3.12-slim

# Establecemos el directorio de trabajo dentro del contenedor
WORKDIR /app/backend

# Copiamos los archivos de requisitos e instalamos las dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# importar el módulo db
ENV PYTHONPATH=/app:/app/backend:/app/db

# Copiamos el código del backend
COPY . .

# Exponemos el puerto en el que correrá FastAPI
EXPOSE 8000

# Comando para ejecutar la aplicación
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
